# This Github workflow
name: build_docker_images

# Controls when the action will run
on:
  push:
    branches: [master]
    # Only run this Github Action if a file containing 'Dockerfile' in its name changed
    paths:
      - "**/image_base/Dockerfile"
  repository_dispatch:
    types: [build_images]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-image-seal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: marblehe/base_seal
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: SEAL/image_base/Dockerfile
          tags: latest
          tag_with_sha: true
  build-image-cingulata:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: marblehe/base_cingulata
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Cingulata/image_base/Dockerfile
          tags: latest
          tag_with_sha: true
  build-image-lobster:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: marblehe/base_lobster
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Lobster/image_base/Dockerfile
          tags: latest
          tag_with_sha: true
