# This Github workflow
name: build_docker_images

# Controls when the action will run
on:
  push:
    branches: [master]
    # Only run this Github Action if a file containing 'Dockerfile' in its name changed
    paths:
      - "**/image_base/Dockerfile"
  repository_dispatch:
    types: [build_images]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-images:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # this must match the tool's directory name in the SoK repo
        tool: [SEAL, Cingulata, Lobster, ALCHEMY, nGraph-HE]
        include:
          - tool: SEAL
            dockerhub_repository: marblehe/base_seal
          - tool: Cingulata
            dockerhub_repository: marblehe/base_cingulata
          - tool: Lobster
            dockerhub_repository: marblehe/base_lobster
          - tool: ALCHEMY
            dockerhub_repository: marblehe/base_alchemy
          - tool: nGraph-HE
            dockerhub_repository: marblehe/base_ngraph-he
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ matrix.dockerhub_repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ${{ matrix.tool }}/image_base/Dockerfile
          tags: latest
          tag_with_sha: true
