# This Github workflow
name: build_docker_images

# Controls when the action will run
on:
  push:
    branches: [master]
    # Only run this Github Action if a file containing 'Dockerfile' in its name changed
    paths:
      - "**/image_base/Dockerfile"
  repository_dispatch:
    types: [build_images]

env:
  DOCKER_BUILDKIT: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-images:
    runs-on: ubuntu-20.04
    # the strategy executes this job for each tool in parallel
    strategy:
      # do not cancel all jobs if any matrix job fails
      fail-fast: false
      matrix:
        include:
          # tool: the directory name in the SoK repository
          # dockerhub_repository: an existing repository on DockerHub
          - tool: SEAL
            dockerhub_repository: marblehe/base_seal
          - tool: Cingulata
            dockerhub_repository: marblehe/base_cingulata
          - tool: Lobster
            dockerhub_repository: marblehe/base_lobster
          - tool: ALCHEMY
            dockerhub_repository: marblehe/base_alchemy
          - tool: SEALion
            dockerhub_repository: marblehe/base_sealion
          - tool: TFHE
            dockerhub_repository: marblehe/base_tfhe
          - tool: PALISADE
            dockerhub_repository: marblehe/base_palisade
          - tool: Concrete
            dockerhub_repository: marblehe/base_concrete
          - tool: EVA
            dockerhub_repository: marblehe/base_eva
    # Compilation is too resource-heavy to be performed on Github actions runner
    #          - tool: nGraph-HE
    #            dockerhub_repository: marblehe/base_ngraph-he

    steps:
      - name: Check out the SoK repository
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ matrix.dockerhub_repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ${{ matrix.tool }}/image_base/Dockerfile
          tags: latest
          tag_with_sha: true
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: ${{ matrix.dockerhub_repository }}
